
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/snap/clion/405/bin/cmake/linux/x64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/snap/clion/405/bin/ninja/linux/x64/"
      - "/home/matthew/.cargo/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/snap/bin/"
    searched_directories:
      - "/snap/clion/405/bin/ninja/linux/x64/uname"
      - "/home/matthew/.cargo/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/snap/clion/405/bin/ninja/linux/x64"
        - "/home/matthew/.cargo/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/snap/bin"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/405/bin/cmake/linux/x64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.14.0-37-generic - x86_64
...
